### ISSUE TITLE
df_destack_themes_indexed.csv does not exist

### ISSUE THREAD

**Issue by twktheainur** [claimskg/claimskg-statistical-observatory#10]
When starting the server for the first time, df_destack_themes_indexed.csv cannot be found and the initial execution fails. 

Creating this file in modules with ",,,,themes,,,," as the sole line allows us to start the server, except that the by themes page is empty. Even after calling the API calls to generate the tree dataframes, this file is not created properly. 

@DadouO

**Comment by DadouO** [comment]
Thanks for raising the problem. This was a coherence problem with the use of paths. The use of pathlib in the generation line has fixed the error on my local run and API call. I did the PR, let me know if it persists.

**Comment by twktheainur** [comment]
@DadouO The problem seems not to occur any longer, the generation_csv_themes REST call now runs, however it seems to be taking a really long time: it's been 3-4 hours so far running at 100% of a CPU core and it still isn't finished
Could there be an infinite loop somewhere? Is there a specific order in which the dataframes should be generated?
