### ISSUE TITLE
File b'/app/modules/df_keywords_exploded.csv' does not exist

### ISSUE THREAD

**Issue by twktheainur** [claimskg/claimskg-statistical-observatory#8]
@DadouO It appears that a resource file is missing when trying to generate the csv themes. 
Is that something that has to be generated? Is there a REST call for it? 

Otherwise, is it possible to add it to the repository?

**Comment by DadouO** [comment]
I changed the destination repository initially it was generated at the root and now as necessary, the generation is on the 'modules' repository. The csv generation theme route must be operational.
